
version: 2

models:
  - name: stg__hosts
    description: "The host staging table"
    columns:
      - name: host_id
        description: "The unique identifier for the host"
        data_tests:
          - unique
          - not_null

      - name: host_name
        description: "The name of the host"
        data_tests:
          - not_null

      - name: is_superhost
        description: "Whether the host is a superhost"
        data_tests:
          - accepted_values:
              values: [0, 1]

  - name: stg__listings
    columns:
      - name: room_type
        description: "The type of room"
        data_tests:
          - accepted_values:
              values: ['Entire home/apt', 'Shared room', 'Private room', 'Hotel room']



